# Generated by Django 2.1.3 on 2018-12-03 20:26

import apps.common.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_full_path', models.CharField(max_length=1024)),
                ('created_at', apps.common.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', apps.common.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('state', models.CharField(max_length=128)),
                ('task_id', models.CharField(max_length=128)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Organization')),
                ('parent_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='FileDataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('storage_full_path', models.CharField(max_length=1024)),
                ('file_name', models.CharField(max_length=256)),
                ('file_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', apps.common.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', apps.common.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Organization')),
                ('parent_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
