# Generated by Django 2.1.3 on 2018-12-01 16:18

import common.fields
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLExperiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('column_usage', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('started', 'Started'), ('progress', 'In progress'), ('done', 'Done'), ('error', 'Error')], default='view', max_length=32)),
                ('errors', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('task_id', models.CharField(max_length=128)),
                ('created_at', common.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', common.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Organization')),
                ('parent_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_key', models.TextField(db_index=True)),
                ('created_at', common.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', common.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('model_type', models.CharField(max_length=128)),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('training_details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('training_time', models.IntegerField(blank=True, null=True)),
                ('metric', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('started', 'Started'), ('progress', 'In progress'), ('done', 'Done'), ('error', 'Error')], default='view', max_length=32)),
                ('errors', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('task_id', models.CharField(max_length=128)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ml.MLExperiment')),
                ('parent_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Organization')),
                ('parent_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
