export const GET_ERRORS = 'GET_ERRORS';

// Auth
export const AUTH_LOGIN_USER_REQUEST = 'AUTH_LOGIN_USER_REQUEST';
export const AUTH_LOGIN_USER_FAILURE = 'AUTH_LOGIN_USER_FAILURE';
export const AUTH_LOGIN_USER_SUCCESS = 'AUTH_LOGIN_USER_SUCCESS';
export const AUTH_LOGOUT_USER = 'AUTH_LOGOUT_USER';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const UNSET_CURRENT_USER = 'UNSET_CURRENT_USER';

// Projects
export const PROJECTS_LOADING = 'PROJECTS_LOADING';
export const GET_PROJECTS = 'GET_PROJECTS';
export const OPEN_PROJECT = 'OPEN_PROJECT';
export const ADD_PROJECT = 'ADD_PROJECT';
export const DELETE_TASK = 'DELETE_PROJECT';

// Project Detail
export const PROJECT_FLOW_LOADING = 'PROJECT_FLOW_LOADING';
export const GET_PROJECT_FLOW = 'GET_PROJECT_FLOW';


// Data Sources
export const DATA_SOURCES_LOADING = 'DATA_SOURCES_LOADING';
export const GET_DATA_SOURCES = 'GET_DATA_SOURCES';
